name: Build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

# TODO: Check that make is pristine instead of rebuilding.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Install goimports
        run: go get golang.org/x/tools/cmd/goimports

      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate code
        run: make

      - name: Build Docker image
        run: docker-compose build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint 1.23.8
        uses: actions-contrib/golangci-lint@v1
        with:
          golangci_lint_version: 1.23.8
